import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import StoreProvider from "@/app/utils/storeProvider";

const inter = Inter({ subsets: ["latin"] });
// inter.className += " bg-center bg-cover";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        // style={{ backgroundImage: "url(/bg.jpg)" }}
      >
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
